#!/bin/bash

# Установка переменных
DOMAIN="yourdomain.com"
CERT_DIR="/etc/ssl/certs"
PRIVATE_KEY_DIR="/etc/ssl/private"
CERT_FILE="$DOMAIN.crt"
PRIVATE_KEY_FILE="$DOMAIN.key"
DAYS_VALID=3650

# Создание каталогов, если они не существуют
mkdir -p $CERT_DIR
mkdir -p $PRIVATE_KEY_DIR

# Генерация самоподписанного сертификата
openssl req -x509 -nodes -days $DAYS_VALID -newkey rsa:2048 \
    -keyout "$PRIVATE_KEY_DIR/$PRIVATE_KEY_FILE" \
    -out "$CERT_DIR/$CERT_FILE" \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=$DOMAIN"

# Настройка прав доступа к файлам ключа и сертификата
chmod 600 "$PRIVATE_KEY_DIR/$PRIVATE_KEY_FILE"
chmod 644 "$CERT_DIR/$CERT_FILE"

# Перезапуск Apache для применения изменений
systemctl restart apache2
